import { Mapping } from '../../Estate';

export const mappingLong: Mapping = {
  // apartmentType: '',
  // attic: '',
  balcony: 'balconyavailable.values[0]',
  bathHasShower: 'bathroomproperties.values', // list
  bathHasTub: 'bathroomproperties.values', // list
  bathHasWc: 'bathroomproperties.values', // list
  // buildingEnergyRatingType: '',
  // buildingType: '',
  builtInKitchen: 'builtin_kitchen.values[0]',
  cellar: 'cellar.values[0]',
  certificateOfEligibilityNeeded: 'housingpermitneeded.values[0]',
  condition: 'condition.values[0]',
  constructionPhase: 'constructionphase.values', // list
  constructionYear: 'yearofconstruction.values[0]',
  courtageNote: 'commissionInformation.values[0]',
  // currency: '',
  descriptionNote: 'textEstate.values[0]',
  // dishwasher: '',
  distanceToAirport: 'traveltimeairport.values[0]',
  distanceToFM: 'traveltimebab.values[0]',
  distanceToMRS: 'traveltimemainstation.values[0]',
  // distanceToPT: '',
  // electricityConsumption: '',
  energyCertificateAvailability: 'energy_certificate_availability.values[0]',
  // energyCertificateCreationDate: '',
  energyConsumptionContainsWarmWater: 'energywithwarmwater.values[0]',
  // energyConsumptionElectricity: '',
  // energyConsumptionHeating: '',
  energyEfficiencyClass: 'energyefficienceclass.values', // list
  energyPerformanceCertificate:
    'energyCertificate.energy_performance_certificate.values[0]',
  // energySourceEnev2014: '',
  estateType: 'estatetype.values', // list
  firingTypes: 'fuelenergy_type.values', // list
  // flatShareSize: '',
  floor: 'floor.values[0]',
  // freeFrom: '',
  furnishing: 'furnished.values[0]',
  furnishingNote: 'textEnvironment.values[0]',
  garden: 'gardenarea.values[0]',
  guestBathroom: 'guesttoilet.values[0]',
  guestToilet: 'guesttoilet.values[0]',
  // hasCourtage: '',
  // heatingConsumption: '',
  heatingType: 'typeofheating.values', // list
  identifier: 'identifier.values[0]',
  interiorQuality: 'qualfitout.values[0]',
  // internetConnection: '',
  // investmentType: '',
  lastRefurbishment: 'lastModernization.values[0]',
  // listed: '',
  // livingInformation: '',
  livingSpace: 'livingarea.values[0]',
  locationNote: 'textLocation.values[0]',
  netFloorSpace: 'livingarea.values[0]',
  // numberOfApartments: '',
  numberOfBathRooms: 'numberbathrooms.values[0]',
  numberOfBedRooms: 'numberbedrooms.values[0]',
  // numberOfCommercialUnits: '',
  numberOfFloors: 'no_of_floors.values[0]',
  // numberOfParkingSpaces: '',
  numberOfRooms: 'rooms.values[0]',
  otherNote: 'textFree.values[0]',
  // oven: '',
  // parkingSituation: '',
  // parkingSpacePrice: '',
  parkingSpaceType: 'parking.values', // list
  // patio: '',
  plotArea: 'plotarea.values[0]',
  price: ['pricesqm.values[0]', 'price.values[0]'],
  rent: ['rentsqf.values[0]', 'rent.values[0]'],
  // refrigerator: '',
  // rented: '',
  // requestedGender: '',
  // residentialUnits: '',
  // smokingAllowed: '',
  // state: '',
  // stove: '',
  // telephoneConnection: '',
  // thermalCharacteristic: '',
  // thermalCharacteristicElectricity: '',
  // thermalCharacteristicHeating: '',
  title: 'headline.values[0]',
  totalFloorSpace: 'totalarea.values[0]',
  // tvConnection: '',
  usableFloorSpace: 'usablearea.values[0]',
  // washingMachine: '',
};

export const estateSchemas = [
  'catering_accommodation_purchase',
  'catering_accommodation_rent',
  'flat_purchase',
  'flat_rent',
  'garage_pitch',
  'garage_pitch_purchase',
  'garage_pitch_rent',
  'house_purchase',
  'houses_rent',
  'investment',
  'land_lease',
  'land_purchase',
  'office_surgery_purchase',
  'office_surgery_rent',
  'other_commercial_estates_purchase',
  'other_commercial_estates_rent',
  'production_halls_purchase',
  'production_halls_rent',
  'shops_commerce_purchase',
  'shops_commerce_rent',
  'temporary_accommodation',
];
