import { Mapping } from '../Estate';

[
  'attic',
  'balcony',
  'buildingEnergyRatingType',
  'cellar',
  'condition',
  'constructionPhase',
  'constructionYear',
  'courtage',
  'descriptionNote',
  'energyCertificateAvailability',
  'energyConsumptionContainsWarmWater',
  'energyPerformanceCertificate',
  'floor',
  'freeFrom',
  'furnishingNote',
  'garden',
  'guestBathroom',
  'guestToilet',
  'handicappedAccessible',
  'heatingType',
  'interiorQuality',
  'lastRefurbishment',
  'listed',
  'locationNote',
  'lodgerFlat',
  'otherNote',
  'parkingSpacePrice',
  'parkingSpaceType',
  'patio',
  'rented',
  'residentialUnits',
  'summerResidencePractical',
  'usableFloorSpace',
];

export const mapping: Mapping = {
  apartmentType: '',
  attic: '',
  balcony: '',
  bathHasShower: '',
  bathHasTub: '',
  bathHasWc: '',
  buildingEnergyRatingType: '',
  buildingType: '',
  builtInKitchen: '',
  cellar: '',
  certificateOfEligibilityNeeded: '',
  condition: '',
  constructionPhase: '',
  constructionYear: '',
  courtageNote: '',
  currency: '',
  descriptionNote: '',
  dishwasher: '',
  distanceToAirport: '',
  distanceToFM: '',
  distanceToMRS: '',
  distanceToPT: '',
  electricityConsumption: '',
  energyCertificateAvailability:
    'energyCertificate.energyCertificateAvailability',
  energyCertificateCreationDate: '',
  energyConsumptionContainsWarmWater: '',
  energyConsumptionElectricity: '',
  energyConsumptionHeating: '',
  energyEfficiencyClass: '',
  energyPerformanceCertificate:
    'energyCertificate.energyPerformanceCertificate',
  energySourceEnev2014: '',
  estateType: '',
  firingTypes: 'firingTypes[0].firingType',
  flatShareSize: '',
  floor: '',
  freeFrom: '',
  furnishing: '',
  furnishingNote: '',
  garden: '',
  guestBathroom: '',
  guestToilet: '',
  hasCourtage: '',
  heatingConsumption: '',
  heatingType: '',
  identifier: 'externalId',
  interiorQuality: '',
  internetConnection: '',
  investmentType: '',
  lastRefurbishment: '',
  listed: '',
  livingInformation: '',
  livingSpace: '',
  locationNote: '',
  netFloorSpace: '',
  numberOfApartments: '',
  numberOfBathRooms: '',
  numberOfBedRooms: '',
  numberOfCommercialUnits: '',
  numberOfFloors: '',
  numberOfParkingSpaces: '',
  numberOfRooms: '',
  otherNote: '',
  oven: '',
  parkingSituation: '',
  parkingSpacePrice: '',
  parkingSpaceType: '',
  patio: '',
  plotArea: '',
  price: '',
  rent: '',
  refrigerator: '',
  rented: '',
  requestedGender: '',
  residentialUnits: '',
  smokingAllowed: '',
  state: 'realEstateState',
  stove: '',
  telephoneConnection: '',
  thermalCharacteristic: '',
  thermalCharacteristicElectricity: '',
  thermalCharacteristicHeating: '',
  title: '',
  totalFloorSpace: '',
  tvConnection: '',
  usableFloorSpace: '',
  washingMachine: '',
};
